version: "2"

services:
  voting-app:
    build: ./voting-app/.
    ports:
      - "5000:80"
    environment:
      - REDIS_HOST=redis

  result-app:
    build: ./result-app/.
    ports:
      - "5001:80"
    environment:
      - DB_HOST=db

  worker:
    build: ./worker
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db

  redis:
    image: redis
    ports: ["6379"]

  db:
    image: postgres:9.4


