version: "2"

services:
  voting-app:
    image: rpatan/voting-app
    ports:
      - "80"
    environment:
      - REDIS_HOST=redis

  result-app:
    image: rpatan/result-app
    ports:
      - "80"
    environment:
      - DB_HOST=db

  worker:
    image: rpatan/worker
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db

  redis:
    image: redis
    expose:
      - "6379"
    environment:
      - constraint:provider==digitalocean

  db:
    image: postgres:9.4
    environment:
      - constraint:provider==digitalocean